Random forest parallelization
smartcorelib/smartcore pull request #137
Opened 2022-07-09 15:25 UTC by daraghk

2022-07-14 01:19 UTC, VolodymyrOrlov commented
@daraghk , thank you very much for your contribution to Smartcore! The code looks good, the only thing that is left are `clippy` warnings and better test coverage. Once you have closed all pending checks we can merge this PR to `development`

2022-07-14 11:37 UTC, daraghk commented
@VolodymyrOrlov happy to contribute! I've fixed the code coverage issue but the linting errors are unrelated to any code I touched - you can see the same issues in the other random forest pr which is open at  the moment.

2022-07-25 18:46 UTC, morenol requested changes
Code looks good to me.

Just an issue with WASM targets and multithreading support.

Regarding the clippy issue, I think that a rebase/merge with `development` will fix that.

2022-07-25 18:46 UTC, morenol commented on src/ensemble/random_forest_classifier.rs
> +        let thread_pool = rayon::ThreadPoolBuilder::new()
It looks like this fail for WASM targets, Could you explore using this https://github.com/GoogleChromeLabs/wasm-bindgen-rayon? or keep the old behavior for `fit` when using `wasm` target, and this one of non `wasm` targets?.

2022-10-31 18:31 UTC, closed without merging

2022-10-31 18:39 UTC, morenol commented
I think that we could do parallelization with a feature flag that is disabled for WASM targets

2022-10-31 19:20 UTC, Mec-iS commented
I know but we have no bandwidth to follow up on all these features, creating a feature for one case can be only an increase in complexity with very few benefits. We need to prioritise or allocate more time or have somebody that carries on the task of extending parallelization to more algorithms.