Move to enum Kernels instead of Structs for hypertuning
smartcorelib/smartcore pull request #169
Opened 2022-09-22 00:42 UTC by montanalow

SVCSearchParameters currently uses a Vec<K> for kernels, which means you can't search across multiple kernel types at the same time. This PR converts K to an enum Kernel type, instead of a generic type, so that multiple kinds of kernels may be compared in the same grid search.

2022-09-22 00:45 UTC, montanalow commented
This is a breaking change, so may require more thought on the approach.

2022-09-26 15:59 UTC, Mec-iS commented
please add the breaking change to the CHANGESLOG

2022-10-01 23:20 UTC, morenol commented
I think that having the `Kernel` trait give us more flexibility. More people could implement their own Kernel and use it without troubles. I think that what we could do for ease of use is convert `Kernels` into an enum and implement `Kernel` for `Kernels`.

2022-10-31 18:18 UTC, Mec-iS requested changes
Please adapt these changes to the new code in development.

`Kernel` is now an object-safe trait. Making an enum of `Kernel`s had been a problem for me because a match expression needs to return the same type. I tried different options but for sure there is something I am missing:
```
pun enum Kernels {
    Linear(LinearKernel),
    RBF(RBFKernel)
    ...
}

match kernel {
    Linear => LinearKernel::default(),  // this returns a LinearKernel type
    RBF => RBFkernel::default(),       // this returns a RBFKernel type
    ...
}
```

2025-07-11 10:45 UTC, closed without merging