[WIP] Add clippy CI job
smartcorelib/smartcore pull request #24
Opened 2020-11-07 00:08 UTC by morenol

2020-11-10 04:41 UTC, morenol commented on src/linalg/mod.rs
> +    fn is_empty(&self) -> bool {
I just implemented this to remove the warning, but not sure if this actually makes sense and has a use case for this library. We can just ignore that warning if this is not needed

2020-11-11 00:19 UTC, VolodymyrOrlov requested changes

2020-11-11 00:19 UTC, VolodymyrOrlov commented on .circleci/config.yml
> +          command: cargo clippy -- -Drust-2018-idioms -Dwarnings
I found that Clippy ignores code behind optional features. The tool generates a bunch of additional errors when the flag `--all-features` is enabled. Hope this won't discourage you from finishing this PR :)
```suggestion
          command: cargo clippy --all-features -- -Drust-2018-idioms -Dwarnings
```

2020-11-11 00:19 UTC, VolodymyrOrlov commented on src/lib.rs
> +#![allow(
Can you either move this block to the top, right under 
```
#![warn(missing_docs)]
#![warn(missing_doc_code_examples)]
```
or move this block close to yours?

2020-11-11 00:22 UTC, VolodymyrOrlov commented
@morenol I like your idea of having a static code analysis tool and the idea of running every PR through this tool. 

Can I also ask you to update [developer's guide page](https://github.com/smartcorelib/smartcorelib.org/blob/development/user_guide/developer.md) with a list of steps every developer should do prior to submitting PR for a review? I am thinking:

1. Run all tests, make sure there are no errors
1. Fix code formatting: cargo fmt
1. Run clippy: cargo clippy --all-features -- -Drust-2018-idioms -Dwarnings

This might be a new section, e.g. Code Quality, or part of other section. 

This info will help developers understand better what steps he/she needs to follow to ensure proper code quality.

2020-11-11 01:45 UTC, VolodymyrOrlov approved these changes
LGTM

2020-11-11 21:11 UTC, merged