Add flag to pretty-print
smartcorelib/smartcore pull request #241
Opened 2022-11-16 01:05 UTC by m7142yosuke

Fixes #225 

### Checklist
- [ ] My branch is up-to-date with development branch.
- [ ] Everything works and tested on latest stable Rust.
- [ ] Coverage and Linting have been applied 

### Current behaviour

Currently println!("{}", &gnb) prints:
```rust
GaussianNB:
inner: BaseNaiveBayes { distribution: GaussianNBDistribution { class_labels: [0, 1, 2], class_count: [50, 50, 50], class_priors: [0.3333333333333333, 0.3333333333333333, 0.3333333333333333], var: [[0.12176398698426993, 0.1422760001411465, 0.0295040034446723, 0.01126400058841702], [0.26110400788880384, 0.09650000076294418, 0.21639999752045114, 0.03832399889564586], [0.3962559386291673, 0.10192399745559833, 0.2984959836425922, 0.07392400431251556]], theta: [[5.006000003814697, 3.41800000667572, 1.4639999961853027, 0.24400000482797624], [5.935999975204468, 2.770000009536743, 4.259999980926514, 1.3259999918937684], [6.588000001907349, 2.9739999914169313, 5.551999988555909, 2.0259999775886537]] }, _phantom_tx: PhantomData, _phantom_ty: PhantomData, _phantom_x: PhantomData, _phantom_y: PhantomData }
```

### New expected behaviour

```rust
GaussianNB:
inner: BaseNaiveBayes {
    distribution: GaussianNBDistribution {
        class_labels: [
            1,
            2,
        ],
        class_count: [
            3,
            3,
        ],
        class_priors: [
            0.3,
            0.7,
        ],
        var: [
            [
                0.666666666666667,
                0.22222222222222232,
            ],
            [
                0.666666666666667,
                0.22222222222222232,
            ],
        ],
        theta: [
            [
                -2.0,
                -1.3333333333333333,
            ],
            [
                2.0,
                1.3333333333333333,
            ],
        ],
    },
    _phantom_tx: PhantomData,
    _phantom_ty: PhantomData,
    _phantom_x: PhantomData,
    _phantom_y: PhantomData,
}
```

### Change logs

I'm just starting to learn rust, so I'm sorry if I'm wrong.
I implemented it differently from the format presented in #225 . Is it better to implement just like the example?

2022-11-16 01:19 UTC, m7142yosuke commented
I'm just starting to learn rust, so I'm sorry if I'm wrong.
I implemented it differently from the format presented in https://github.com/smartcorelib/smartcore/issues/225 . Is it better to implement just like the example?

2022-11-16 09:44 UTC, Mec-iS commented
thanks a lot!

could you try to do the same for other structures that implement `Display`? Could you find a way to avoid printing the `_phantom` fields?

2022-11-22 02:02 UTC, m7142yosuke commented
@Mec-iS 
I tried. Can you review it?

2022-11-22 10:20 UTC, Mec-iS commented
Good job.

This could be merged but it will fix only the Gaussian, what about the other distributions? Please double check that all of them return well formatted output.

2022-11-22 10:59 UTC, Mec-iS requested changes
please see comments for desirable changes

2026-01-18 03:34 UTC, closed without merging